import json
import os

notebook_content = {
  "cells": [
    {
      "cell_type": "code",
      "metadata": {
        "id": "e9212c51",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "93075aa9-bfee-45ea-b970-8c002eb97e1d"
      },
      "source": [
        "from google.colab import drive\n",
        "drive.mount('/content/drive')"
      ],
      "execution_count": None,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "B2F5YlDRR2Hv"
      },
      "source": [
        "# CrackSegDiff: Simplified Training & Inference\n",
        "Automated setup, data preparation (First 500 Test / 2000 Train), training, and testing."
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {
        "id": "MRQyR0WNR2Hx",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000
        },
        "outputId": "2fa64d4c-8080-4e8e-ed1a-4c328b65cba0"
      },
      "outputs": [],
      "source": [
        "# 1. Setup Environment & Weights\n",
        "# @title Configuration\n",
        "TRAIN_MODEL = True # @param {type:\"boolean\"}\n",
        "DRIVE_MODEL_DIR = \"/content/drive/MyDrive/CrackSegDiff/models\"\n",
        "\n",
        "import os\n",
        "os.makedirs(DRIVE_MODEL_DIR, exist_ok=True)\n",
        "\n",
        "!nvidia-smi\n",
        "import os\n",
        "if not os.path.exists('CrackSegDiff'):\n",
        "    !git clone https://github.com/Ludwig-H/CrackSegDiff.git\n",
        "%cd CrackSegDiff\n",
        "!git pull\n",
        "\n",
        "target_file_gd = 'CrackSegDiff/guided_diffusion/gaussian_diffusion.py'\n",
        "if os.path.exists(target_file_gd):\n",
        "    with open(target_file_gd, 'r') as f: content = f.read()\n",
        "    content = content.replace('beta_end = scale * 0.02', 'beta_end = scale * 0.02\\n        if beta_end > 0.999: beta_end = 0.999')\n",
        "    with open(target_file_gd, 'w') as f: f.write(content)\n",
        "\n",
        "# Downgrade PyTorch to stable 2.4.0 for guaranteed Mamba compatibility\n",
        "print(\"Installing PyTorch 2.4.0 compatible with Mamba wheels...\")\n",
        "!pip uninstall -y torch torchvision torchaudio\n",
        "!pip install torch==2.4.0 torchvision==0.19.0 torchaudio==2.4.0 --index-url https://download.pytorch.org/whl/cu121\n",
        "\n",
        "!pip install -r requirement.txt\n",
        "\n",
        "# Force install pre-built wheels for Mamba-SSM and Causal-Conv1d to avoid compilation errors and ensure GPU speed\n",
        "print(\"Installing Optimized Mamba Kernels...\")\n",
        "import torch\n",
        "cuda_version = torch.version.cuda.replace('.', '')\n",
        "torch_version = torch.__version__.split('+')[0].replace('.', '')\n",
        "# Assuming standard Colab PyTorch 2.x and CUDA 11.8 or 12.x\n",
        "# We use the releases from Dao-AILab which are reliable\n",
        "!pip install ninja  # Speeds up compilation\n",
        "!pip install causal-conv1d>=1.0.0 --no-build-isolation -v\n",
        "!pip install mamba-ssm>=1.0.1 --no-build-isolation -v\n",
        "\n",
        "# If the above standard install fails (it tries to build), we could try finding wheels:\n",
        "# (But usually --no-build-isolation helps or just standard pip works if env is clean)\n",
        "\n",
        "# Verify installation\n",
        "try:\n",
        "    import mamba_ssm\n",
        "    print(\"SUCCESS: Mamba SSM installed successfully! GPU acceleration enabled (x10 speed).\")\n",
        "except ImportError:\n",
        "    print(\"WARNING: Mamba SSM installation failed.\")\n",
        "    print(\"Fallback to Pure Python active (SLOWER).\")\n",
        "\n",
        "# Download Pretrained Weights\n",
        "!mkdir -p pretrained_weights\n",
        "!gdown 1JYqMxM5dbCLZ-WGPKtIofYJhj0VPuy3l -O pretrained_weights/vssm_base_0229_ckpt_epoch_237.pth\n",
        "\n",
        "# Patch Hardcoded Paths\n",
        "target_file = 'CrackSegDiff/guided_diffusion/unet.py'\n",
        "new_path = os.path.abspath('pretrained_weights/vssm_base_0229_ckpt_epoch_237.pth')\n",
        "if os.path.exists(target_file):\n",
        "    with open(target_file, 'r') as f: content = f.read()\n",
        "    content = content.replace('/home/dell/jlc/segdiff/pre_trained_weights/vssm_base_0229_ckpt_epoch_237.pth', new_path)\n",
        "    with open(target_file, 'w') as f: f.write(content)\n",
        "    print(\"Path patched successfully.\")"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {
        "id": "pEWy7SZUR2Hy"
      },
      "outputs": [],
      "source": [
        "# 2. Prepare Data (First 500 Test / 2000 Train)\n",
        "!rm -rf data && mkdir -p data\n",
        "%cd data\n",
        "!gdown 1qnLMCeon7LJjT9H0ENiNF5sFs-F7-NvK -O data.zip\n",
        "!unzip -q -o data.zip\n",
        "%cd ..\n",
        "\n",
        "import os, glob, shutil\n",
        "print(\"Organizing Data...\")\n",
        "\n",
        "# Find folders\n",
        "try:\n",
        "    src_img = glob.glob('data/**/img/fused', recursive=True)[0]\n",
        "    src_lbl = glob.glob('data/**/lbs', recursive=True)[0]\n",
        "except IndexError:\n",
        "    # Fallback if 'fused' not found, try 'intensity'\n",
        "    print(\"Fused folder not found, checking intensity...\")\n",
        "    src_img = glob.glob('data/**/img/intensity', recursive=True)[0]\n",
        "    src_lbl = glob.glob('data/**/lbs', recursive=True)[0]\n",
        "\n",
        "print(f\"Images source: {src_img}\")\n",
        "print(f\"Labels source: {src_lbl}\")\n",
        "\n",
        "# Get sorted file lists\n",
        "img_files = sorted(glob.glob(os.path.join(src_img, '*')))\n",
        "lbl_files = sorted(glob.glob(os.path.join(src_lbl, '*.bmp')))\n",
        "\n",
        "# Split: First 500 Test, Rest Train\n",
        "test_pairs = list(zip(img_files[:500], lbl_files[:500]))\n",
        "train_pairs = list(zip(img_files[500:], lbl_files[500:]))\n",
        "\n",
        "print(f\"Test Set: {len(test_pairs)} (First 500)\")\n",
        "print(f\"Train Set: {len(train_pairs)} (Rest)\")\n",
        "\n",
        "# Copy to formatted directories\n",
        "train_dir = os.path.abspath('data/Train')\n",
        "test_dir = os.path.abspath('data/Test')\n",
        "\n",
        "for pairs, dest in [(train_pairs, train_dir), (test_pairs, test_dir)]:\n",
        "    os.makedirs(os.path.join(dest, '5d'), exist_ok=True)\n",
        "    os.makedirs(os.path.join(dest, 'mask'), exist_ok=True)\n",
        "    for img, mask in pairs:\n",
        "        shutil.copy(img, os.path.join(dest, '5d'))\n",
        "        shutil.copy(mask, os.path.join(dest, 'mask'))\n",
        "print(\"Data preparation complete.\")"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "DIAGNOSTIC_CELL"
      },
      "source": [
        "# @title 🔍 DIAGNOSTIC: Check Training Data Format\n",
        "import os\n",
        "import glob\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "from PIL import Image\n",
        "\n",
        "print(\"--- DIAGNOSTIC START ---\")\n",
        "\n",
        "# 1. Locate the unzipped data (from previous cell)\n",
        "try:\n",
        "    src_img_fused = glob.glob('data/**/img/fused', recursive=True)[0]\n",
        "    print(f\"Found fused images folder: {src_img_fused}\")\n",
        "\n",
        "    # 2. Load a sample\n",
        "    sample_files = sorted(glob.glob(os.path.join(src_img_fused, '*.png')))\n",
        "    if not sample_files:\n",
        "        print(\"No PNG files found in fused folder.\")\n",
        "    else:\n",
        "        sample_path = sample_files[0]\n",
        "        print(f\"Analyzing sample: {sample_path}\")\n",
        "\n",
        "        img = Image.open(sample_path)\n",
        "        print(f\"Format: {img.format}, Mode: {img.mode}, Size: {img.size}\")\n",
        "\n",
        "        arr = np.array(img)\n",
        "        print(f\"Shape: {arr.shape}, Dtype: {arr.dtype}\")\n",
        "        print(f\"Min: {arr.min()}, Max: {arr.max()}\")\n",
        "\n",
        "        if arr.ndim == 3:\n",
        "            # RGB / RGBA\n",
        "            print(\"Channels analysis:\")\n",
        "            channels = ['R (Intensity?)', 'G (Range?)', 'B', 'A']\n",
        "            for i in range(min(4, arr.shape[2])):\n",
        "                c_name = channels[i]\n",
        "                ch = arr[..., i]\n",
        "                print(f\"  Channel {c_name}: Min={ch.min()}, Max={ch.max()}, Mean={ch.mean():.2f}\")\n",
        "\n",
        "            # Visualization\n",
        "            fig, axes = plt.subplots(1, min(4, arr.shape[2]+1), figsize=(15, 4))\n",
        "            axes[0].imshow(arr)\n",
        "            axes[0].set_title(\"Full Image\")\n",
        "            for i in range(min(3, arr.shape[2])):\n",
        "                axes[i+1].imshow(arr[..., i], cmap='gray')\n",
        "                axes[i+1].set_title(f\"Channel {i}\")\n",
        "            plt.show()\n",
        "        else:\n",
        "            print(\"Image is 2D (Grayscale). This implies Single Modality or Palette?\")\n",
        "            plt.imshow(arr, cmap='gray')\n",
        "            plt.show()\n",
        "\n",
        "except IndexError:\n",
        "    print(\"Could not locate 'img/fused' folder. Ensure the previous cell (Data Preparation) ran successfully.\")\n",
        "except Exception as e:\n",
        "    print(f\"An error occurred: {e}\")\n",
        "\n",
        "print(\"--- DIAGNOSTIC END ---\")"
      ],
      "execution_count": None,
      "outputs": []
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {
        "id": "DQw8EdbbR2Hy",
        "outputId": "f2f37ad3-0227-47c5-be5b-972f46279625",
        "colab": {
          "base_uri": "https://localhost:8080/"
        }
      },
      "outputs": [],
      "source": [
        "# 3. Train Model\n",
        "import os\n",
        "import shutil\n",
        "import glob\n",
        "\n",
        "data_dir = os.path.abspath('data/Train')\n",
        "out_dir = os.path.abspath('results/train_output')\n",
        "os.makedirs(out_dir, exist_ok=True)\n",
        "\n",
        "if TRAIN_MODEL:\n",
        "    print(\"Starting Training...\")\n",
        "    !python CrackSegDiff/segmentation_train.py --data_dir {data_dir} --out_dir {out_dir} --image_size 256 --num_channels 96 --class_cond False --num_res_blocks 2 --num_heads 1 --learn_sigma True --use_scale_shift_norm False --attention_resolutions 16 --diffusion_steps 500 --noise_schedule linear --rescale_learned_sigmas False --rescale_timesteps False --lr 5e-5 --batch_size 8 --save_interval 5000 --lr_anneal_steps 40000\n",
        "\n",
        "    # Save to Drive\n",
        "    print(f\"Backing up model to {DRIVE_MODEL_DIR}...\")\n",
        "    for model_file in glob.glob(os.path.join(out_dir, '*.pt')):\n",
        "        shutil.copy(model_file, DRIVE_MODEL_DIR)\n",
        "    print(\"Backup complete.\")\n",
        "else:\n",
        "    print(\"Training skipped (TRAIN_MODEL=False).\")"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {
        "id": "25zAeOGsR2Hy"
      },
      "outputs": [],
      "source": [
        "# 4. Inference\n",
        "import glob, os\n",
        "\n",
        "# Select Model\n",
        "if TRAIN_MODEL:\n",
        "    models = sorted(glob.glob('results/train_output/*.pt'))\n",
        "    model_path = models[-1] if models else \"pretrained_weights/savedmodel100000.pt\"\n",
        "else:\n",
        "    print(f\"Using model from Drive: {DRIVE_MODEL_DIR}\")\n",
        "    drive_models = sorted(glob.glob(os.path.join(DRIVE_MODEL_DIR, '*.pt')))\n",
        "    model_path = drive_models[-1] if drive_models else \"pretrained_weights/savedmodel100000.pt\"\n",
        "\n",
        "test_dir = os.path.abspath('data/Test')\n",
        "print(f\"Using model: {model_path}\")\n",
        "\n",
        "for modality in ['intensity', 'range', 'fused']: # , 'filtered', 'all'\n",
        "    out_path = f\"results/test_output_{modality}\"\n",
        "    os.makedirs(out_path, exist_ok=True)\n",
        "    print(f\"Testing {modality}...\")\n",
        "    !python CrackSegDiff/segmentation_sample.py --data_dir {test_dir} --out_dir {out_path} --model_path {model_path} --modality {modality} --image_size 256 --num_channels 96 --class_cond False --num_res_blocks 2 --num_heads 1 --learn_sigma True --use_scale_shift_norm False --attention_resolutions 16 --diffusion_steps 500 --noise_schedule linear --rescale_learned_sigmas False --rescale_timesteps False --num_ensemble 1\n",
        "    print(f\"Done {modality}\")"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": None,
      "metadata": {
        "id": "KtEvRC4TR2Hz"
      },
      "outputs": [],
      "source": [
        "# 5. Zip Results\n",
        "!zip -r results.zip results"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "f8f1cd92"
      },
      "source": [
        "# 6. Robustness Benchmark (Inference on Pre-generated Noisy Data)\n",
        "# Uses noisy data from /content/drive/MyDrive/Datasets/FIND/Noisy\n",
        "# Saves results to /content/drive/MyDrive/Datasets/FIND/Results/CrackSegDiff_noise\n",
        "\n",
        "import numpy as np\n",
        "import os\n",
        "import glob\n",
        "import shutil\n",
        "from skimage import io\n",
        "from tqdm import tqdm\n",
        "\n",
        "# --- Configuration --- \n",
        "NOISY_INPUT_ROOT = \"/content/drive/MyDrive/Datasets/FIND/Noisy\"\n",
        "RESULTS_ROOT = \"/content/drive/MyDrive/Datasets/FIND/Results/CrackSegDiff_noise\"\n",
        "TEMP_DATA_ROOT = os.path.abspath(\"temp_inference_noisy\")\n",
        "CLEAN_TEST_DIR = os.path.abspath('data/Test') # Source for masks\n",
        "\n",
        "# Select Model (Same logic as above)\n",
        "if 'TRAIN_MODEL' in locals() and not TRAIN_MODEL:\n",
        "    drive_models = sorted(glob.glob(os.path.join(DRIVE_MODEL_DIR, '*.pt')))\n",
        "    MODEL_PATH = drive_models[-1] if drive_models else \"pretrained_weights/savedmodel100000.pt\"\n",
        "else:\n",
        "    models = sorted(glob.glob('results/train_output/*.pt'))\n",
        "    MODEL_PATH = models[-1] if models else \"pretrained_weights/savedmodel100000.pt\"\n",
        "\n",
        "print(f\"Using Model for Benchmark: {MODEL_PATH}\")\n",
        "\n",
        "speckle_vars = [0.0, 0.01, 0.05, 0.10, 0.3, 0.5]\n",
        "range_sigmas = [0.0, 0.01, 0.05, 0.10, 0.3, 0.5]\n",
        "\n",
        "experiments = [\n",
        "    (\"speckle_intensity\", speckle_vars),\n",
        "    (\"gauss_range\", range_sigmas),\n",
        "    (\"both\", range_sigmas)\n",
        "]\n",
        "def _noise_tag(x: float, ndigits: int = 4):\n",
        "    return f\"{x:.{ndigits}f}\".replace(\".\", \"p\")\n",
        "\n",
        "# Ensure we have masks ready\n",
        "clean_masks = sorted(glob.glob(os.path.join(CLEAN_TEST_DIR, 'mask', '*.bmp')))\n",
        "clean_masks = clean_masks[:500]\n",
        "if not clean_masks:\n",
        "    print(\"WARNING: No masks found in clean test dir. Masks will be missing in temp dir.\")\n",
        "\n",
        "for exp_name, levels in experiments:\n",
        "    print(f\"\\n=== Experiment: {exp_name} ===\")\n",
        "\n",
        "    for lvl in levels:\n",
        "        lvl = float(lvl)\n",
        "        tag = _noise_tag(lvl)\n",
        "\n",
        "        # Input Directory (Drive)\n",
        "        noisy_src_dir = os.path.join(NOISY_INPUT_ROOT, exp_name, tag)\n",
        "        # Output Directory (Drive)\n",
        "        final_dest_dir = os.path.join(RESULTS_ROOT, exp_name, tag, \"test_output_fused\")\n",
        "\n",
        "        if not os.path.exists(noisy_src_dir):\n",
        "            print(f\"Skipping {exp_name}/{tag}: Input directory not found ({noisy_src_dir})\")\n",
        "            continue\n",
        "\n",
        "        if os.path.exists(final_dest_dir) and len(glob.glob(os.path.join(final_dest_dir, '*.png'))) >= 500:\n",
        "            print(f\"Skipping {exp_name}/{tag}: Results already exist ({len(os.listdir(final_dest_dir)) } files)\")\n",
        "            continue\n",
        "\n",
        "        print(f\"Processing {exp_name} - Level {lvl} (Tag: {tag})\")\n",
        "\n",
        "        # 1. Prepare Temp Directory\n",
        "        if os.path.exists(TEMP_DATA_ROOT): shutil.rmtree(TEMP_DATA_ROOT)\n",
        "        temp_5d = os.path.join(TEMP_DATA_ROOT, '5d')\n",
        "        temp_mask = os.path.join(TEMP_DATA_ROOT, 'mask')\n",
        "        os.makedirs(temp_5d, exist_ok=True)\n",
        "        os.makedirs(temp_mask, exist_ok=True)\n",
        "\n",
        "        # 2. Reconstruct Fused Images from Drive (Intensity + Range)\n",
        "        # Files are named imXXXXX_intensity.png / imXXXXX_range.png\n",
        "        int_files = sorted(glob.glob(os.path.join(noisy_src_dir, '*_intensity.png')))\n",
        "        print(f\"Found {len(int_files)} intensity images in {noisy_src_dir}\")\n",
        "\n",
        "        count = 0\n",
        "        for int_path in int_files:\n",
        "            fname = os.path.basename(int_path)\n",
        "            # fname format: imXXXXX_intensity.png\n",
        "            base_name = fname.replace('_intensity.png', '') # imXXXXX\n",
        "            range_path = os.path.join(noisy_src_dir, f\"{base_name}_range.png\")\n",
        "\n",
        "            if not os.path.exists(range_path):\n",
        "                # Fallback? Should not happen if generated correctly.\n",
        "                continue\n",
        "\n",
        "            # Read Images\n",
        "            img_i = io.imread(int_path)\n",
        "            img_r = io.imread(range_path)\n",
        "\n",
        "            # Ensure dimensions match\n",
        "            if img_i.shape[:2] != img_r.shape[:2]:\n",
        "                continue\n",
        "\n",
        "            # Stack (H, W, 3) -> R=Int, G=Range, B=0\n",
        "            H, W = img_i.shape[:2]\n",
        "            fused = np.zeros((H, W, 3), dtype=np.uint8)\n",
        "            fused[..., 0] = img_i if img_i.ndim==2 else img_i[...,0]\n",
        "            fused[..., 1] = img_r if img_r.ndim==2 else img_r[...,0]\n",
        "            # Channel 2 is 0\n",
        "\n",
        "            # Save as imXXXXX.png (Standard format for CrackSegDiff)\n",
        "            # Note: The output will be imXXXXX_output_ens.png\n",
        "            io.imsave(os.path.join(temp_5d, f\"{base_name}.png\" ), fused, check_contrast=False)\n",
        "            count += 1\n",
        "\n",
        "        # Copy Masks (Assumes matching IDs in Clean Test Dir)\n",
        "        # We blindly copy all first 500 clean masks, assuming IDs match 1-500.\n",
        "        for mask_path in clean_masks:\n",
        "            shutil.copy(mask_path, temp_mask)\n",
        "\n",
        "        print(f\"Prepared {count} images for inference.\")\n",
        "\n",
        "        # 3. Run Inference\n",
        "        temp_out_dir = os.path.join(TEMP_DATA_ROOT, \"output\")\n",
        "        os.makedirs(temp_out_dir, exist_ok=True)\n",
        "\n",
        "        !python CrackSegDiff/segmentation_sample.py --data_dir {TEMP_DATA_ROOT} --out_dir {temp_out_dir} --model_path {MODEL_PATH} --modality fused --image_size 256 --num_channels 96 --class_cond False --num_res_blocks 2 --num_heads 1 --learn_sigma True --use_scale_shift_norm False --attention_resolutions 16 --diffusion_steps 500 --noise_schedule linear --rescale_learned_sigmas False --rescale_timesteps False --num_ensemble 1\n",
        "\n",
        "        # 4. Save to Drive\n",
        "        print(f\"Saving results to: {final_dest_dir}\")\n",
        "        os.makedirs(final_dest_dir, exist_ok=True)\n",
        "\n",
        "        copied = 0\n",
        "        for png in glob.glob(os.path.join(temp_out_dir, \"*.png\")):\n",
        "            shutil.copy(png, final_dest_dir)\n",
        "            copied += 1\n",
        "        print(f\"Saved {copied} result files.\")\n",
        "\n",
        "print(\"Robustness Benchmark (Inference Only) Complete.\")"
      ],
      "execution_count": None,
      "outputs": []
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.8.5"
    },
    "colab": {
      "provenance": [],
      "gpuType": "L4",
      "machine_shape": "hm"
    },
    "accelerator": "GPU"
  },
  "nbformat": 4,
  "nbformat_minor": 0
}

with open("CrackSegDiff_Colab.ipynb", "w") as f:
    json.dump(notebook_content, f, indent=1)